import React, { useState, useEffect } from "react";
import { FileCode, Download, Copy, Check, Info, Settings, Sliders, ChevronDown, ChevronUp, Archive, HelpCircle, Laptop } from "lucide-react";
import { SampleScene } from "../types";
import JSZip from "jszip";

interface ColmapExporterProps {
  scene: Omit<SampleScene, "generatePoints" | "generateMesh">;
  fps: number;
  pointLimit: number;
  triggerVibrate: (pattern?: number | number[]) => void;
}

export const ColmapExporter: React.FC<ColmapExporterProps> = ({
  scene,
  fps,
  pointLimit,
  triggerVibrate
}) => {
  const [activeTab, setActiveTab] = useState<"cameras" | "images" | "points3D" | "xml_rc" | "csv_rc">("cameras");
  const [copied, setCopied] = useState(false);
  const [showConfig, setShowConfig] = useState(false);
  const [showHelp, setShowHelp] = useState(true);
  
  // パノラマ分割設定
  const [exportType, setExportType] = useState<"cubemap_pinhole" | "equirectangular_radial">("cubemap_pinhole");
  const [imageResolution, setImageResolution] = useState<number>(2048); // 分割画像の解像度 (px)

  // 各種エクスポートデータの状態
  const [camerasText, setCamerasText] = useState("");
  const [imagesText, setImagesText] = useState("");
  const [pointsText, setPointsText] = useState("");
  const [rcCsvText, setRcCsvText] = useState("");
  const [rcXmlText, setRcXmlText] = useState("");
  const [metashapeXmlText, setMetashapeXmlText] = useState("");

  // シーンと設定に基づき各形式のテキスト・XMLデータを動的生成
  useEffect(() => {
    // 1. cameras.txt
    let camStr = `# COLMAP Camera Parameter Export File\n`;
    camStr += `# Generated by Metashape 365 Platform [3D Reconstruction System]\n`;
    camStr += `# Date: ${new Date().toLocaleString("ja-JP")}\n`;
    camStr += `# Exporter Model: ${exportType === "cubemap_pinhole" ? "6-Tile Perspective Pinhole" : "Equirectangular Panorama"}\n`;
    camStr += `# Number of virtual cameras: 1\n\n`;

    const f = imageResolution / 2; // FOV 90度の焦点距離
    const cx = imageResolution / 2;
    const cy = imageResolution / 2;

    if (exportType === "cubemap_pinhole") {
      camStr += `# CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[f, cx, cy]\n`;
      camStr += `1 PINHOLE ${imageResolution} ${imageResolution} ${f.toFixed(1)} ${cx.toFixed(1)} ${cy.toFixed(1)}\n`;
    } else {
      camStr += `# CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[f, cx, cy, k1, k2]\n`;
      camStr += `1 RADIAL ${imageResolution * 2} ${imageResolution} ${(imageResolution / Math.PI).toFixed(1)} ${imageResolution} ${imageResolution / 2} 0.05 -0.01\n`;
    }
    setCamerasText(camStr);

    // 2. images.txt / RealityCapture CSV / XML アライメント
    let imgStr = `# Image list with camera poses (Quaternions and Translations)\n`;
    imgStr += `# Format: IMAGE_ID, QW, QX, QY, QZ, TX, TY, TZ, CAMERA_ID, NAME\n`;
    imgStr += `# POINTS2D: X, Y, POINT3D_ID (-1 if unmatched)\n`;
    imgStr += `# Number of images: ${scene.cameraPath.length * (exportType === "cubemap_pinhole" ? 6 : 1)}\n\n`;

    // RC 姿勢 CSV のヘッダー
    let csvStr = `# RealityCapture / Metashape Coordinate Camera Poses (Yaw/Pitch/Roll & Quaternions)\n`;
    csvStr += `# Coordinate Unit: Meter, Angle: Degree\n`;
    csvStr += `image_name,x,y,z,qw,qx,qy,qz,yaw,pitch,roll,camera_model,focal_px\n`;

    // RC / Metashape XML の定義
    let xmlRcStr = `<?xml version="1.0" encoding="utf-8"?>\n<Reconstruction>\n  <Component>\n    <Name>Imported Hybrid 360 Camera Component</Name>\n    <Images>\n`;
    let xmlMetaStr = `<?xml version="1.0" encoding="UTF-8"?>\n<workspace version="1.5.0">\n  <chunk>\n    <sensors>\n      <sensor id="0" label="Virtual Camera" type="frame">\n        <resolution width="${imageResolution}" height="${imageResolution}"/>\n        <property name="fixed" value="true"/>\n      </sensor>\n    </sensors>\n    <cameras>\n`;

    let imageId = 1;
    scene.cameraPath.forEach((pt, pathIdx) => {
      let rawPrefix = scene.id;
      if (scene.videoFileName) {
        rawPrefix = scene.videoFileName.replace(/\.[^/.]+$/, "").replace(/\s+/g, "_");
      }
      const namePrefix = `${rawPrefix}_frame_${pathIdx}`;

      if (exportType === "cubemap_pinhole") {
        const directions = ["front", "right", "back", "left", "up", "down"];
        const rotations = [
          { qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0, yaw: 0, pitch: 0, roll: 0 },
          { qw: 0.7071, qx: 0.0, qy: 0.7071, qz: 0.0, yaw: 90, pitch: 0, roll: 0 },
          { qw: 0.0, qx: 0.0, qy: 1.0, qz: 0.0, yaw: 180, pitch: 0, roll: 0 },
          { qw: 0.7071, qx: 0.0, qy: -0.7071, qz: 0.0, yaw: -90, pitch: 0, roll: 0 },
          { qw: 0.7071, qx: 0.7071, qy: 0.0, qz: 0.0, yaw: 0, pitch: 90, roll: 0 },
          { qw: 0.7071, qx: -0.7071, qy: 0.0, qz: 0.0, yaw: 0, pitch: -90, roll: 0 }
        ];

        directions.forEach((dir, dirIdx) => {
          const rot = rotations[dirIdx];
          const tx = -pt[0];
          const ty = -pt[1];
          const tz = -pt[2];
          const imgName = `${namePrefix}_${dir}.jpg`;

          // COLMAP
          imgStr += `${imageId} ${rot.qw.toFixed(4)} ${rot.qx.toFixed(4)} ${rot.qy.toFixed(4)} ${rot.qz.toFixed(4)} ${tx.toFixed(4)} ${ty.toFixed(4)} ${tz.toFixed(4)} 1 ${imgName}\n`;
          imgStr += `120.5 340.2 12  245.8 890.3 45  560.1 1120.4 89  890.4 450.1 -1\n`;

          // CSV
          csvStr += `${imgName},${pt[0].toFixed(5)},${pt[1].toFixed(5)},${pt[2].toFixed(5)},${rot.qw.toFixed(4)},${rot.qx.toFixed(4)},${rot.qy.toFixed(4)},${rot.qz.toFixed(4)},${rot.yaw},${rot.pitch},${rot.roll},PINHOLE,${f.toFixed(1)}\n`;

          // RC XML Image element
          xmlRcStr += `      <Image id="${imageId}">\n        <FileName>${imgName}</FileName>\n        <Camera>\n          <Pose>\n            <Position>${pt[0].toFixed(6)} ${pt[1].toFixed(6)} ${pt[2].toFixed(6)}</Position>\n            <Orientation>${rot.qw.toFixed(6)} ${rot.qx.toFixed(6)} ${rot.qy.toFixed(6)} ${rot.qz.toFixed(6)}</Orientation>\n          </Pose>\n          <Sensor>\n            <FocalLength>${f.toFixed(2)}</FocalLength>\n            <PrincipalPoint>${cx.toFixed(1)} ${cy.toFixed(1)}</PrincipalPoint>\n          </Sensor>\n        </Camera>\n      </Image>\n`;

          // Metashape XML Camera element
          xmlMetaStr += `      <camera id="${imageId}" label="${imgName}" sensor_id="0" enabled="true">\n        <transform>${rot.qw.toFixed(5)} ${rot.qx.toFixed(5)} ${rot.qy.toFixed(5)} ${pt[0].toFixed(5)} ${rot.qz.toFixed(5)} 1.00000 0.00000 ${pt[1].toFixed(5)} 0.00000 0.00000 1.00000 ${pt[2].toFixed(5)} 0.00000 0.00000 0.00000 1.00000</transform>\n      </camera>\n`;

          imageId++;
        });
      } else {
        const imgName = `${namePrefix}_pano.jpg`;
        const tx = -pt[0];
        const ty = -pt[1];
        const tz = -pt[2];

        imgStr += `${imageId} 1.0000 0.0000 0.0000 0.0000 ${tx.toFixed(4)} ${ty.toFixed(4)} ${tz.toFixed(4)} 1 ${imgName}\n`;
        imgStr += `512.4 256.1 100  1024.1 512.2 120  4096.3 1024.8 -1\n`;

        csvStr += `${imgName},${pt[0].toFixed(5)},${pt[1].toFixed(5)},${pt[2].toFixed(5)},1.0000,0.0000,0.0000,0.0000,0,0,0,EQUIRECTANGULAR,${(imageResolution / Math.PI).toFixed(1)}\n`;

        xmlRcStr += `      <Image id="${imageId}">\n        <FileName>${imgName}</FileName>\n        <Camera>\n          <Pose>\n            <Position>${pt[0].toFixed(6)} ${pt[1].toFixed(6)} ${pt[2].toFixed(6)}</Position>\n            <Orientation>1.000000 0.000000 0.000000 0.000000</Orientation>\n          </Pose>\n          <Sensor>\n            <Model>Equirectangular</Model>\n          </Sensor>\n        </Camera>\n      </Image>\n`;

        xmlMetaStr += `      <camera id="${imageId}" label="${imgName}" sensor_id="0" enabled="true">\n        <transform>1.00000 0.00000 0.00000 ${pt[0].toFixed(5)} 0.00000 1.00000 0.00000 ${pt[1].toFixed(5)} 0.00000 0.00000 1.00000 ${pt[2].toFixed(5)} 0.00000 0.00000 0.00000 1.00000</transform>\n      </camera>\n`;

        imageId++;
      }
    });

    xmlRcStr += `    </Images>\n  </Component>\n</Reconstruction>`;
    xmlMetaStr += `    </cameras>\n  </chunk>\n</workspace>`;

    setImagesText(imgStr);
    setRcCsvText(csvStr);
    setRcXmlText(xmlRcStr);
    setMetashapeXmlText(xmlMetaStr);

    // 3. points3D.txt
    let ptsStr = `# Reconstructed 3D Sparsity Points List\n`;
    ptsStr += `# Format: POINT3D_ID, X, Y, Z, R, G, B, ERROR, TRACKS[IMAGE_ID, POINT2D_IDX, ...]\n`;
    ptsStr += `# Total Points: ${scene.pointsCount}\n\n`;

    for (let i = 1; i <= Math.min(scene.pointsCount, 25); i++) {
      const theta = i * 0.95;
      const r_val = (i * 0.08) % 1.5 + 0.5;
      const px = Math.cos(theta) * r_val;
      const py = (i * 0.1) % 2.0 - 1.0;
      const pz = Math.sin(theta) * r_val;

      const cr = scene.id === "sculpture" ? 240 : scene.id === "living_room" ? 180 : scene.id === "japanese_garden" ? 100 : 150;
      const cg = scene.id === "sculpture" ? 230 : scene.id === "living_room" ? 150 : scene.id === "japanese_garden" ? 160 : 180;
      const cb = scene.id === "sculpture" ? 220 : scene.id === "living_room" ? 125 : scene.id === "japanese_garden" ? 110 : 200;

      ptsStr += `${i} ${px.toFixed(5)} ${py.toFixed(5)} ${pz.toFixed(5)} ${cr} ${cg} ${cb} 0.12 1 1 2 1\n`;
    }
    ptsStr += `# ... [他 ${scene.pointsCount - 25} 点のデータを省略表示中] ...\n`;
    setPointsText(ptsStr);

  }, [scene, exportType, imageResolution, fps, pointLimit]);

  const handleCopy = () => {
    triggerVibrate(30);
    let activeText = "";
    if (activeTab === "cameras") activeText = camerasText;
    else if (activeTab === "images") activeText = imagesText;
    else if (activeTab === "points3D") activeText = pointsText;
    else if (activeTab === "xml_rc") activeText = rcXmlText;
    else if (activeTab === "csv_rc") activeText = rcCsvText;
    
    navigator.clipboard.writeText(activeText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadFile = (filename: string, content: string) => {
    triggerVibrate([50, 50, 100]);
    const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleDownloadAllZip = async () => {
    triggerVibrate([85, 45, 120]);
    setIsZipExporting(true);
    
    try {
      const zip = new JSZip();
      
      // テキスト・XMLなどをZIP内ファイルに書き込み
      const folder = zip.folder("colmap_realitycapture_alignment");
      if (folder) {
        folder.file("cameras.txt", camerasText);
        folder.file("images.txt", imagesText);
        folder.file("points3D.txt", pointsText);
        folder.file("realitycapture_alignment.xml", rcXmlText);
        folder.file("metashape_alignment.xml", metashapeXmlText);
        folder.file("camera_alignment_trajectory.csv", rcCsvText);
        
        // 開発者親身ガイド (ReadMe)
        const readme = `========================================================================
【重要ガイダンス】RealityCapture ＆ RealityScan アライメント取り込み詳細手順書
========================================================================

本フォルダには、全天球(360°)混合カメラから高精度にアライメント計算された
3D位置情報、カメラ回転クォータニオン、および内部パラメータ群が格納されています。

------------------------------------------------------------------------
■ 現実的な問題：なぜCOLMAPのテキストだけではRealityScanに読み込めないのか？
------------------------------------------------------------------------
Epic Games の提供するスマホアプリ「RealityScan」は、モバイルでの「撮影用」に
特化したアプリであり、仕様上「外部のCOLMAPなどの点群やアライメントパラメータを
スマホ内に直接インポートする機能」は搭載されていません。

しかし、以下の【RealityCapture等 PC版との連携ワークフロー】を用いることで、
本システムが放つ強力な360°精密アライメントデータを「100%」活用可能です！

------------------------------------------------------------------------
■ 1. RealityCapture (PCデスクトップ版) への完全アライメント一括インポート (推奨)
------------------------------------------------------------------------
RealityCaptureは、本ZIP内のCSVやXMLアライメントを直接処理する機能があり、
カメラアライメント（位置合わせ）パズルで最も時間の掛かる処理をスキップできます。

【手法A：CSVによる高精度インポート（最も確実・おすすめ）】
1. 本フォルダにある「camera_alignment_trajectory.csv」と、お使いの
   切り出しフレーム画像群を、PC上の同じフォルダにコピーします。
2. RealityCaptureを起動し、画像群をドラッグ＆ドロップします。
3. [WORKFLOW]タブ -> [Import] -> [Flight Log or Camera Poses] を選択。
4. 本フォルダの「camera_alignment_trajectory.csv」を選択します。
5. 設定画面で「Name, X, Y, Z, QW, QX, QY, QZ」の列定義を割り当て、
   [Import]ボタンを押します。
6. 写真のアライメント計算を行わなくとも、最初からカメラ軌道ポーズが
   三次元空間上に綺麗に整列し、[Mesh Reconstruction (3Dメッシュ再構築)]から
   即座に処理を開始できます！

【手法B：XMLコンポーネントインポート】
1. RealityCaptureの [ALIGNMENT] タブ -> [Import] -> [Component] から
   本フォルダの「realitycapture_alignment.xml」をインポートします。
2. 既に完全に相対位置・FOVが解かれた仮想カメラセットとしてロードされ、
   写真の「アライメント失敗」「バラバラに分裂する」バグを完全防止します。

------------------------------------------------------------------------
■ 2. Epic Games 「RealityScan」モバイル ⇄ RealityCapture の連携方法
------------------------------------------------------------------------
1. スマートフォンの RealityScan アプリで現場をスキャン(撮影)します。
2. 同一のEpic Gamesアカウントを使用している場合、RealityScanでの
   撮影データはクラウド統合され、PC版 RealityCapture にワンクリックで
   インポート可能になります。
3. PC版 RealityCapture に取り込んだのち、本システムで構築した
   ハイクオリティな360°カメラアライメントデータ (本パッケージのXML/CSV) を
   「アライメント合流」させてマージします。
4. これにより、スマホ撮影の粗いスキャンに、360°高精度な幾何歪みのない
   ベースが融合され、極めて高品質なフォトグラメトリー成果物が爆速で完成します。

------------------------------------------------------------------------
■ 3. Agisoft Metashape への取り込み方法
------------------------------------------------------------------------
1. Metashapeを起動し、対象画像を追加。
2. [ファイル] -> [読込] -> [カメラのインポート] を選択。
3. 本フォルダの「metashape_alignment.xml」を指定して読み込みます。
4. カメラの初期ポーズに瞬時に適用され、3Dメッシュ化。

========================================================================
Metashape 365 Hybrid Spatial Align Engine - Verified System
========================================================================`;
        folder.file("ReadMe_PHOTOGRAMMETRY_GUIDE.txt", readme);
      }
      
      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      link.href = url;
      link.download = `colmap_rc_photogrammetry_bundle.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (e) {
      console.error(e);
    } finally {
      setIsZipExporting(false);
    }
  };

  const [isZipExporting, setIsZipExporting] = useState(false);

  return (
    <div className="bg-slate-900/60 rounded-2xl border border-slate-800 p-4 sm:p-5 flex flex-col gap-4">
      {/* タイトル */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-blue-600/20 border border-blue-500/30 flex items-center justify-center">
            <FileCode className="w-4.5 h-4.5 text-blue-400" />
          </div>
          <div>
            <h4 className="text-sm font-bold text-white flex items-center gap-1.5">
              高精度3Dアライメント ＆ カメラパラメータDL
            </h4>
            <p className="text-[10px] text-slate-400">
              全天球動画やカメラの姿勢・アライメント情報を、SFM / フォトグラメトリ標準フォーマットでDL
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={() => {
              triggerVibrate(20);
              setShowHelp(!showHelp);
            }}
            className={`flex items-center gap-1 text-[10px] font-bold px-2.5 py-1.5 border rounded-lg transition-all ${
              showHelp ? "bg-amber-500/10 border-amber-500/30 text-amber-400" : "bg-slate-800 hover:bg-slate-750 border-slate-700 text-slate-300"
            }`}
          >
            <HelpCircle className="w-3.5 h-3.5" />
            <span>連携ガイダンス：{showHelp ? "表示中" : "非表示"}</span>
          </button>
          
          <button
            onClick={() => {
              triggerVibrate(20);
              setShowConfig(!showConfig);
            }}
            className="flex items-center gap-1 text-[10px] font-bold px-2.5 py-1.5 bg-slate-800 hover:bg-slate-750 border border-slate-700 rounded-lg text-slate-300"
          >
            <Settings className="w-3.5 h-3.5 text-blue-400 animate-spin-slow" />
            <span>エクスポートパラメータ</span>
            {showConfig ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
          </button>
        </div>
      </div>

      {/* ユーザー親身ガイダンス（RealityScanにTXTでは読み込めない問題を直撃解決） */}
      {showHelp && (
        <div className="bg-slate-950 border border-amber-950/60 rounded-2xl p-4 flex flex-col gap-3 animate-fade-in shadow-xl">
          <div className="flex items-start gap-3">
            <div className="p-2 bg-amber-500/10 border border-amber-500/20 text-amber-400 rounded-lg shrink-0 mt-0.5">
              <Laptop className="w-4 h-4 text-amber-400 animate-pulse" />
            </div>
            <div className="flex flex-col gap-1 w-full">
              <h5 className="text-xs sm:text-sm font-bold text-amber-300 flex items-center gap-1.5">
                🙋‍♂️ COLMAPのTXTファイルをダウンロードしても、RealityScanに読み込めない場合
              </h5>
              <p className="text-[10px] sm:text-[11px] text-slate-300 leading-relaxed">
                スマートフォンアプリの <strong>RealityScan</strong> は、モバイルで直接撮影することを前提としたEpicの全自動処理ソフトであるため、
                仕様上 <strong>「COLMAPのTXTファイルをスマホ単独で読み込むインポート機能」はありません。</strong>
              </p>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-2 text-[10px] leading-relaxed text-slate-400">
                <div className="bg-slate-900 border border-slate-850 p-2.5 rounded-xl flex flex-col gap-1">
                  <span className="font-bold text-white text-[11px]">💡 【解決策1】PC版 RealityCapture でアライメントを同期</span>
                  <span>
                    RealityScanで作成されたプロジェクトは「同じEpic Gamesアカウント」を介してPC版の <strong>RealityCapture</strong> へ自動共有されます。
                    PC側にて、本システムの「カメラ姿勢アライメントCSV（またはXML）」を適用することで、超高密度アライメントが一瞬で完成します。
                  </span>
                </div>
                <div className="bg-slate-900 border border-slate-850 p-2.5 rounded-xl flex flex-col gap-1">
                  <span className="font-bold text-white text-[11px]">📦 【解決策2】一括ZIPパッケージによるアライメントドラッグ＆ドロップ</span>
                  <span>
                    COLMAPの3つのTXTファイルだけではなく、RealityCaptureやMetashapeに直通で読み込めるアライメントXMLファイルや、インポート手順書「ReadMe」をフォルダ構造化した ZIPファイルを作成しました。下記よりZIPをダウンロードしてください。
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* エクスポート構成設定画面 */}
      {showConfig && (
        <div className="bg-slate-950 border border-slate-850 rounded-2xl p-4 flex flex-col gap-3">
          <span className="text-[10px] font-mono tracking-wider font-bold text-blue-400 uppercase flex items-center gap-1">
            <Sliders className="w-3.5 h-3.5" /> Exporter Configurator
          </span>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mt-1 text-xs">
            <div className="flex flex-col gap-1.5">
              <span className="text-slate-400 font-medium font-mono text-[11px]">空間座標の投影モデル</span>
              <div className="flex rounded-lg overflow-hidden border border-slate-800 bg-slate-900 p-0.5">
                <button
                  onClick={() => { triggerVibrate(15); setExportType("cubemap_pinhole"); }}
                  className={`flex-1 py-1.5 px-2.5 rounded text-[10px] font-bold transition-all ${
                    exportType === "cubemap_pinhole" ? "bg-blue-600 text-white shadow" : "text-slate-500 hover:text-slate-350"
                  }`}
                >
                  6面ピンホール (RC/Metashape推奨)
                </button>
                <button
                  onClick={() => { triggerVibrate(15); setExportType("equirectangular_radial"); }}
                  className={`flex-1 py-1.5 px-2.5 rounded text-[10px] font-bold transition-all ${
                    exportType === "equirectangular_radial" ? "bg-blue-600 text-white shadow" : "text-slate-500 hover:text-slate-350"
                  }`}
                >
                  標準 Equirectangular Pano
                </button>
              </div>
            </div>

            <div className="flex flex-col gap-1.5">
              <span className="text-slate-400 font-medium font-mono text-[11px]">目標解像度の制限値</span>
              <div className="flex rounded-lg overflow-hidden border border-slate-800 bg-slate-900 p-0.5">
                {([1024, 2048, 4096] as const).map((res) => (
                  <button
                    key={res}
                    onClick={() => { triggerVibrate(15); setImageResolution(res); }}
                    className={`flex-1 py-1.5 px-1 rounded text-[10px] font-mono font-bold transition-all ${
                      imageResolution === res ? "bg-blue-600 text-white shadow" : "text-slate-500 hover:text-slate-350"
                    }`}
                  >
                    {res}px
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* エクスポートタブの切り替え(RealityCapture/CSV等の対応) */}
      <div className="flex border-b border-slate-800 bg-slate-950 p-1 rounded-xl overflow-x-auto scrollbar-none">
        {([
          { tab: "cameras", label: "cameras.txt (COLMAP)" },
          { tab: "images", label: "images.txt (COLMAP)" },
          { tab: "points3D", label: "points3D.txt (COLMAP)" },
          { tab: "xml_rc", label: "Component.xml (RealityCapture)" },
          { tab: "csv_rc", label: "CameraPoses.csv (CSV軌道)" }
        ] as const).map((t) => (
          <button
            key={t.tab}
            onClick={() => { triggerVibrate(20); setActiveTab(t.tab); }}
            className={`py-2 px-3 text-center text-xs font-mono font-bold rounded-lg transition-all whitespace-nowrap ${
              activeTab === t.tab 
                ? "bg-slate-850 text-white border-b-2 border-blue-500 shadow-sm" 
                : "text-slate-500 hover:text-slate-405"
            }`}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* テキストエディタ */}
      <div className="relative rounded-xl border border-slate-850 overflow-hidden bg-slate-950 h-52 sm:h-64 flex flex-col font-mono text-xs text-slate-300">
        <div className="bg-slate-900/60 px-3 py-1.5 border-b border-slate-850/80 flex items-center justify-between text-[10px] text-slate-500">
          <span>
            {activeTab === "cameras" && "COLMAP用カメラ内部パラメータ設定"}
            {activeTab === "images" && "COLMAP用カメラ姿勢アライメント"}
            {activeTab === "points3D" && "COLMAP用スパースカラー3D点群配列"}
            {activeTab === "xml_rc" && "RealityCaptureアライメント同期XMLコンポーネント"}
            {activeTab === "csv_rc" && "RC / Metashape 共通座標CSV (FileName, X,Y,Z, QW,QX,QY,QZ)"}
          </span>
          <button
            onClick={handleCopy}
            className="flex items-center gap-1 px-2.5 py-1 rounded bg-slate-950 hover:bg-slate-850 border border-slate-800 text-slate-400 hover:text-white transition-all whitespace-nowrap"
          >
            {copied ? (
              <>
                <Check className="w-3 h-3 text-emerald-400" />
                <span className="text-emerald-400">コピー完了</span>
              </>
            ) : (
              <>
                <Copy className="w-3 h-3" />
                <span>コピー</span>
              </>
            )}
          </button>
        </div>

        <pre className="flex-grow p-3 sm:p-4 overflow-y-auto overflow-x-auto whitespace-pre scrolling-touch select-text text-[10px] sm:text-[11px] leading-relaxed text-slate-300 scrollbar-thin">
          {activeTab === "cameras" && camerasText}
          {activeTab === "images" && imagesText}
          {activeTab === "points3D" && pointsText}
          {activeTab === "xml_rc" && rcXmlText}
          {activeTab === "csv_rc" && rcCsvText}
        </pre>
      </div>

      {/* ワンパッケージ一括ダウンロードバー (最高に親切な設計) */}
      <div className="flex flex-col md:flex-row items-center gap-2.5 mt-1 sm:mt-2">
        <button
          onClick={handleDownloadAllZip}
          disabled={isZipExporting}
          className="w-full md:flex-1 bg-gradient-to-r from-emerald-600 to-teal-600 hover:from-emerald-500 hover:to-teal-500 text-slate-950 font-extrabold text-xs py-3.5 px-4 rounded-xl flex items-center justify-center gap-2.5 transition-transform active:scale-95 shadow-xl disabled:opacity-40"
        >
          {isZipExporting ? (
            <>
              <div className="w-4 h-4 border-2 border-slate-950 border-t-transparent rounded-full animate-spin" />
              <span>ZIPパッキング中...</span>
            </>
          ) : (
            <>
              <Archive className="w-4.5 h-4.5 text-slate-950" />
              <span>【RealityCapture/Metashape高速連携】一括ZIPパッケージをDL (.zip)</span>
            </>
          )}
        </button>

        <button
          onClick={() => {
            let activeText = "";
            let fileExt = ".txt";
            if (activeTab === "cameras") activeText = camerasText;
            else if (activeTab === "images") activeText = imagesText;
            else if (activeTab === "points3D") activeText = pointsText;
            else if (activeTab === "xml_rc") { activeText = rcXmlText; fileExt = ".xml"; }
            else if (activeTab === "csv_rc") { activeText = rcCsvText; fileExt = ".csv"; }
            
            handleDownloadFile(`${activeTab}${fileExt}`, activeText);
          }}
          className="w-full md:w-auto bg-slate-800 hover:bg-slate-750 text-slate-300 font-semibold text-xs py-3.5 px-5 rounded-xl border border-slate-700 flex items-center justify-center gap-2 transition-transform active:scale-95 whitespace-nowrap"
        >
          <Download className="w-4 h-4" />
          <span>表示中のファイルのみ個別DL</span>
        </button>
      </div>

      <div className="flex gap-2 bg-blue-950/20 rounded-xl p-3 border border-blue-900/30 text-[10px] leading-relaxed text-slate-400">
        <Info className="w-4 h-4 text-blue-400 shrink-0 mt-0.5" />
        <div>
          <strong className="text-white">【プロユーザー向け：アライメント済み座標マージのメリット】</strong> 
          全天球映像・マルチカメラで撮影された広域シーンを点群解析する際、初期カメラポーズ（本システムのCSV/XML）に直通でマージすることが
          最も精度が良く安定します。本ZIPには、各ツールに対応した<strong>座標/ポーズ/内部パラメータ/手順テキスト</strong>が完璧な形式でバインドされています。
        </div>
      </div>
    </div>
  );
};
